# Generated by Django 5.0.4 on 2024-06-29 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('enunciado', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('rubrica', models.TextField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parcial', models.IntegerField()),
                ('promedio_parcial', models.IntegerField()),
                ('examen_quimestral', models.IntegerField()),
                ('supletorio', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Citacion',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('representante_legal', models.CharField(max_length=100)),
                ('gravedad', models.CharField(max_length=50)),
                ('motivo', models.TextField()),
                ('fecha_emision', models.DateField()),
                ('fecha_asistencia', models.DateField()),
                ('advertencia', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conducta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('incidente', models.TextField()),
                ('tipo_conducta', models.CharField(max_length=50)),
                ('descripcion_adicional', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('dia', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_finalizacion', models.TimeField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uvirtual.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_horas', models.IntegerField()),
                ('aula', models.CharField(max_length=100)),
                ('dia', models.IntegerField()),
                ('hora', models.TimeField()),
                ('asistencia', models.BooleanField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
